repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        args: ["--line-length", "120"]
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]
      - id: mypy
        name: mypy
        language: system
        args: ["--explicit-package-bases"]
        entry: mypy
        types: [python]
      - id: pylint
        name: pylint
        language: system
        entry: pylint
        types: [python]
